### ISSUE TITLE
Nav Bar does not collapse

### ISSUE THREAD

**Issue by JStuve** [cvasqu09/Live#21]
The nar bar does not collapse into hamburger mode upon resizing.

If the **nav bar is temporary**, **close this issue**

http://prntscr.com/itd1k1

**Comment by cvasqu09** [comment]
The nav-bar in its current state is temporary but I think that is something Dhruuv could work on. Leaving the issue open. Will assign to him once he joins the repo.

**Comment by JStuve** [comment]
Solved with: ca6a47f
